import { useEffect, useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import { ApiClient } from './lib/api'
import { RightPanelTabs } from './components/RightPanelTabs'
import { StatusBanner } from './components/StatusBanner'
import { CompareMessageCard } from './components/CompareMessageCard'
import type { ChatMessage, ChatMode, ChatSession, CompareResponse, RAGStats, SystemStatus } from './types'

const KEY='novel-rag-agent:sessions'; const now=()=>new Date().toISOString(); const id=()=>crypto.randomUUID();
const modes: Array<{k:ChatMode;label:string;exp?:boolean}>=[{k:'chat',label:'普通问答'},{k:'rag',label:'RAG问答'},{k:'compare',label:'RAG对比'},{k:'agent',label:'Agent任务'},{k:'kg',label:'KG问答',exp:true},{k:'graph_rag',label:'GraphRAG',exp:true}]
const newSession=():ChatSession=>({id:id(),title:'新对话',created_at:now(),updated_at:now(),messages:[]})
const norm=(ss:any):ChatSession=>({...ss,id:ss?.id||id(),title:ss?.title||'新对话',created_at:ss?.created_at||now(),updated_at:ss?.updated_at||now(),messages:(ss?.messages||[]).map((m:any)=>({id:m?.id||id(),role:m?.role||'assistant',content:m?.content||'',created_at:m?.created_at||now(),mode:m?.mode||'chat',citations:m?.citations||[],retrieved_docs:m?.retrieved_docs||[],retrieval_metrics:m?.retrieval_metrics,kg_paths:m?.kg_paths||[],agent_trace:m?.agent_trace||null,used_tools:m?.used_tools||[],raw:m?.raw||{}}))})
const friendly=(msg:string)=>{const t=(msg||'').toLowerCase(); if(t.includes('all connection attempts failed')) return 'LLM 后端连接失败，请检查 Ollama 是否启动。'; if(t.includes('model')&&t.includes('not found')) return '模型未找到，请检查 LLM_MODEL_NAME 是否与 ollama list 一致。'; if(t.includes('huggingface')||t.includes('sentence-transformers')) return 'Embedding/Rerank 模型加载失败，请检查 EMBEDDING_MODEL/RERANK_MODEL 是否为本地路径。'; if(t.includes('neo4j')) return 'Neo4j 未连接，KG/GraphRAG 功能暂不可用。'; return '请求失败，请查看后端日志。'}

export function App(){
  const [baseUrl,setBaseUrl]=useState(import.meta.env.VITE_API_BASE_URL??'http://127.0.0.1:8000'); const api=useMemo(()=>new ApiClient(baseUrl),[baseUrl])
  const [sessions,setSessions]=useState<ChatSession[]>([]); const [activeId,setActiveId]=useState(''); const [search,setSearch]=useState(''); const [mode,setMode]=useState<ChatMode>('rag'); const [query,setQuery]=useState(''); const [showRetrieval,setShowRetrieval]=useState(true); const [loading,setLoading]=useState(false); const [selectedMsgId,setSelectedMsgId]=useState(''); const [banner,setBanner]=useState<any>(null); const [stats,setStats]=useState<RAGStats|null>(null); const [system,setSystem]=useState<SystemStatus|null>(null); const [docs,setDocs]=useState<any[]>([])
  useEffect(()=>{try{const raw=localStorage.getItem(KEY); if(raw){const arr=(JSON.parse(raw)||[]).map(norm); setSessions(arr); setActiveId(arr[0]?.id||'')} else {const s=newSession(); setSessions([s]); setActiveId(s.id)}}catch{localStorage.removeItem(KEY); const s=newSession(); setSessions([s]); setActiveId(s.id)}},[])
  useEffect(()=>{if(sessions.length) localStorage.setItem(KEY,JSON.stringify(sessions))},[sessions])
  const active=sessions.find(s=>s.id===activeId)??sessions[0]; const selected=active?.messages.find(m=>m.id===selectedMsgId)??active?.messages.filter(m=>m.role==='assistant').at(-1)??null
  const refresh=async()=>{try{const [s,d,sys]=await Promise.all([api.getRagStats(),api.getDocuments(),api.getSystemStatus()]); setStats(s); setDocs(d.documents); setSystem(sys)}catch(e:any){setBanner({tone:'error',text:friendly(e.message)})}}; useEffect(()=>{refresh()},[baseUrl])
  const patch=(fn:(s:ChatSession)=>ChatSession)=>setSessions(prev=>prev.map(s=>s.id===active.id?fn(s):s)); const append=(m:ChatMessage)=>patch(s=>({...s,title:s.messages.length?s.title:(m.role==='user'?m.content.slice(0,20):s.title),updated_at:now(),messages:[...s.messages,m]}))
  const send=async()=>{ if(!query.trim()||!active) return; append({id:id(),role:'user',content:query,created_at:now(),mode}); setLoading(true); try{ if((mode==='kg'||mode==='graph_rag') && !(system?.neo4j?.connected && system?.kg_tool?.enabled)) throw {message:'KG/GraphRAG 需要先启用 Neo4j 和 KG 查询工具，当前暂不可用。'}; let a:ChatMessage; if(mode==='compare'){const r:CompareResponse=await api.compare({session_id:active.id,query,stream:false,show_retrieval:true,use_kg:false}); a={id:id(),role:'assistant',created_at:now(),mode,content:'compare',retrieved_docs:r.retrieved_docs||[],retrieval_metrics:r.rag_retrieval_metrics,raw:r}} else if(mode==='agent'){const r=await api.agent({session_id:active.id,query,stream:false,use_rag:true,show_retrieval:true,use_kg:false}); a={id:id(),role:'assistant',created_at:now(),mode,content:r.answer||'Agent任务已完成，但没有生成有效总结。',used_tools:r.used_tools||[],agent_trace:r.metadata?.final_state,raw:r}} else {const use_rag=mode==='rag'||mode==='graph_rag'; const use_kg=mode==='kg'||mode==='graph_rag'; const r=await api.ask({session_id:use_rag?active.id:`${active.id}:plain`,query,stream:false,use_rag,show_retrieval:use_rag?showRetrieval:false,use_kg}); a={id:id(),role:'assistant',created_at:now(),mode,content:r.answer||'',citations:r.citations||[],retrieved_docs:r.retrieved_docs||[],retrieval_metrics:r.metadata?.retrieval_metrics,used_tools:r.used_tools||[],kg_paths:r.kg_hits as any,raw:r}} append(a); setSelectedMsgId(a.id); setQuery('')}catch(e:any){setBanner({tone:'error',text:friendly(e.message||'')})} setLoading(false)}
  const filtered=sessions.filter(s=>s.title.toLowerCase().includes(search.toLowerCase()))
  return <div className='app3'>{banner&&<StatusBanner tone={banner.tone} text={banner.text}/>}<aside className='sidebar'><h2>Novel RAG Agent</h2><button onClick={()=>{const s=newSession(); setSessions([s,...sessions]); setActiveId(s.id)}}>+ New Chat</button><button className='ghost' onClick={()=>{localStorage.removeItem(KEY); const s=newSession(); setSessions([s]); setActiveId(s.id)}}>清空本地历史</button><input placeholder='搜索会话' value={search} onChange={e=>setSearch(e.target.value)}/>{filtered.map(s=><div key={s.id} className={`session ${s.id===activeId?'active':''}`}><button onClick={()=>setActiveId(s.id)}>{s.title}</button><button onClick={()=>{const t=prompt('重命名',s.title); if(t) setSessions(p=>p.map(x=>x.id===s.id?{...x,title:t}:x))}}>✎</button><button onClick={()=>{const next=sessions.filter(x=>x.id!==s.id); setSessions(next); if(activeId===s.id&&next[0]) setActiveId(next[0].id)}}>🗑</button></div>)}</aside><main className='chat'><header><h3>{active?.title||'Chat'}</h3><div className='mode'>{modes.map(m=>{const kgAvailable = !!(system?.neo4j?.connected && system?.kg_tool?.enabled); const disabled=(m.k==='kg'||m.k==='graph_rag')&&!kgAvailable; return <button key={m.k} disabled={disabled} title={m.exp?'实验功能 / 开发中':''} className={mode===m.k?'pill on':'pill'} onClick={()=>setMode(m.k)}>{m.label}{m.exp?'(实验)':''}</button>})}</div></header><section className='stream'>{active?.messages.map(m=><div key={m.id} className={`msg ${m.role}`} onClick={()=>m.role==='assistant'&&setSelectedMsgId(m.id)}><div className='bubble'>{m.role==='assistant'&&m.mode==='compare'?<CompareMessageCard raw={m.raw}/>:m.role==='assistant'?<ReactMarkdown>{m.content}</ReactMarkdown>:m.content}</div></div>)}{loading&&<div className='typing'>Assistant is typing…</div>}</section><footer><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder='输入问题，Enter发送 / Shift+Enter换行'/>{(mode==='rag' || mode==='compare') ? <label><input type='checkbox' checked={showRetrieval} onChange={e=>setShowRetrieval(e.target.checked)}/>show retrieval</label> : null}<button disabled={loading} onClick={send}>发送</button></footer></main><RightPanelTabs message={selected} stats={stats} system={system} onRefresh={refresh} docs={docs} onDelete={async(id:string)=>{await api.deleteDocument(id);refresh()}} onIngest={async(p:any)=>{await api.ingest(p);refresh()}} onUpload={async(file:File)=>{await api.upload(file); refresh(); setBanner({tone:'success', text:'上传成功并已重建索引'})}} /></div>
}
